name: Publish LiquidJava Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  checks:
    uses: ./.github/workflows/test.yml

  publish:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Download checked extension
        uses: actions/download-artifact@v4
        with:
          name: liquid-java-vsix

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Publish to VS Code Marketplace
        run: vsce publish --packagePath liquid-java.vsix -p ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX Marketplace
        run: npx ovsx publish liquid-java.vsix --pat ${{ secrets.OVSX_TOKEN }}
